# ip字典
GeoBlockFileName = "./data/GeoLiteCity-Blocks.csv"
GeoLocationFileName = "./data/GeoLiteCity-Location.csv"

# 广告字典
AdFileName = "./data/ad_info.txt"

# 1:debug 2:info 3:warn 4:error 5:fatal
LogLevel = 1
AdServerLogFileName = "./log/ad_server.log"
SearchLogFileName = "./log/ad_search.log"
ImpressionLogFileName = "./log/ad_impression.log"
ClickLogFileName = "./log/ad_click.log"
ConversionLogFileName = "./log/ad_conversion.log"

# track url
ImpressionTrackUrlPrefix = "http://localhost:8001/ad/impression"
ClickTrackUrlPrefix = "http://localhost:8001/ad/click"
ConversionTrackUrlPrefix = "http://localhost:8001/ad/conversion"
